version: 2
updates:
- package-ecosystem: gradle
  directory: "/server"
  schedule:
    interval: weekly
    time: "12:00"
    timezone: America/Chicago
  open-pull-requests-limit: 100
  ignore:
  - dependency-name: io.javalin:javalin
    versions:
    - 3.13.0
    - 3.13.3
    - 3.13.5
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - 5.7.0
    - 5.7.1
  - dependency-name: org.mockito:mockito-core
    versions:
    - 3.7.7
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - 5.7.0
    - 5.7.1
  - dependency-name: com.google.guava:guava
    versions:
    - 30.1-jre
